---
- name: Playbook
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: "Install pip dependencies"
      pip:
        name:
          - google-cloud-vision
          - opencv-python
          - pytesseract
          - pillow
          - imutils
          - numpy



